model:
  model_name: "conv_classify"
  model:
    class_path: src.models.classification.ConvClassify
    init_args:
      in_size: 784
      out_size: 10
  mean: 0.
  std: 1.
  optimizer:
    class_path: pyro.optim.Adam
    init_args:
      - {lr: 0.001, betas: [0.9, 0.999]}
  criterion:
    class_path: pyro.infer.Trace_ELBO
