model:
  model:
    class_path: src.models.regression.MLERegression
    init_args:
      in_size: 8
      hidden_size: 128
      out_size: 1
  mean: 0. #MUST BE FLOATS OTHERWISE RESULT IN ERRORS
  std: 1. #MUST BE FLOATS OTHERWISE RESULT IN ERRORS
  sigma_bound: 5. #MUST BE FLOATS OTHERWISE RESULT IN ERRORS
  optimizer:
    class_path: pyro.optim.Adam
    init_args:
      - {lr: 0.0000000000001, betas: [0.9, 0.999]}
  criterion:
    class_path: pyro.infer.Trace_ELBO
