model:
  model:
    class_path: src.models.classification.ConvClassify
    init_args:
      in_size: 32
      out_size: 10
      in_channels: 3
  optimizer_args:
    lr: 0.001
    betas: [0.9, 0.999]
