model:
  model:
    class_path: src.models.classification.DeepMLEClassify
    init_args:
      in_size: 3072
      hidden_size: 1000
      out_size: 10
  optimizer_args:
    lr: 0.001
    betas: [0.9, 0.999]
