model:
  model:
    class_path: src.models.classification.DeepMLEClassify
    init_args:
      in_size: 784
      hidden_size: 1000
      out_size: 10
      activation:
        class_path: torch.nn.ReLU
  optimizer_args:
    lr: 0.001
    betas: [0.9, 0.999]
