model:
  model:
    class_path: src.models.classification.LeNet
    init_args:
      in_channels: 1
      n_classes: 10
      activation:
        class_path: torch.nn.ReLU
  lr: 0.001
data:
  dataset: "MNIST"
  dataset_path: "datasets"
  num_workers: 16
  train_batch_size: 256
  test_batch_size: 256
