model:
  model:
    class_path: src.models.MLEClassify
    init_args:
      in_size: 784
      hidden_size: 128
      out_size: 10
      activation: "relu"
  lr: 0.001
data:
  dataset: "MNIST"
  dataset_path: "datasets"
  num_workers: 16
  train_batch_size: 128
  valtest_batch_size: 128
