model:
  model:
    class_path: src.models.classification.ConvClassify
    init_args:
      in_size: 28
      out_size: 10
      in_channels: 1
  prior_mean: 0.
  prior_std: None # value or kaiming
  q_mean: 0.
  q_std: 1.
  optimizer:
    class_path: pyro.optim.Adam
    init_args:
      - {lr: 0.001, betas: [0.9, 0.999], weight_decay: 0.00005}
  criterion:
    class_path: pyro.infer.Trace_ELBO
