model:
  model:
    class_path: src.models.classification.DeepMLEClassify
    init_args:
      in_size: 784
      hidden_size: 1000
      out_size: 10
  prior_mean: 0.
  prior_loc: 1. # value or kaiming
  q_mean: 0.
  q_loc: 1.
  mean: 0. #MUST BE FLOATS OTHERWISE RESULT IN ERRORS
  std: 1. #MUST BE FLOATS OTHERWISE RESULT IN ERRORS
  optimizer:
    class_path: pyro.optim.Adam
    init_args:
      - {lr: 0.001, betas: [0.9, 0.999]}
  criterion:
    class_path: pyro.infer.Trace_ELBO
