model:
  model:
    class_path: src.models.regression.LINRegression
    init_args:
      in_size: 3
      out_size: 1
  mean: 0. #MUST BE FLOATS OTHERWISE RESULT IN ERRORS
  weight_std: 1. #MUST BE FLOATS OTHERWISE RESULT IN ERRORS
  bias_std: 10.
  sigma_bound: 10.
  optimizer:
    class_path: pyro.optim.Adam
    init_args:
      - {lr: 0.03, betas: [0.9, 0.999]}
  criterion:
    class_path: pyro.infer.Trace_ELBO
