model:
  model:
    class_path: src.models.regression.RotateNet
    init_args:
  mean: 0. #MUST BE FLOATS OTHERWISE RESULT IN ERRORS
  weight_std: 0.03 #MUST BE FLOATS OTHERWISE RESULT IN ERRORS
  bias_std: 0.03
  sigma_bound: 0.2
  optimizer:
    class_path: pyro.optim.Adam
    init_args:
      - {lr: 0.001, betas: [0.9, 0.999]}
  criterion:
    class_path: pyro.infer.Trace_ELBO
