seed_everything: 42
trainer:
  logger: true
  checkpoint_callback: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
      monitor: val/loss
  default_root_dir: null
  device: "cuda:0"
  log_gpu_memory: null
  max_epochs: 50
  precision: 16
