seed_everything: 42
trainer:
  logger: true
  enable_checkpointing: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
      init_args:
        monitor: validation/accuracy
        mode: max
  default_root_dir: lightning_logs/FashionMNIST/ConvClassify-LeakyReLU_01
  gpus: 1
  log_gpu_memory: null
  max_epochs: 50
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  precision: 16
  num_sanity_val_steps: 0
  resume_from_checkpoint: null
  profiler: null
  stochastic_weight_avg: false
