seed_everything: 42
trainer:
  logger: true
  checkpoint_callback: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
      monitor: val/loss
  default_root_dir: null
  gpus: 1
  log_gpu_memory: null
  max_epochs: 31
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  precision: 16
  num_sanity_val_steps: 0
  resume_from_checkpoint: null
  profiler: null
  deterministic: true
  stochastic_weight_avg: false
