model:
  model:
    class_path: src.models.regression.UNet
    init_args:
      in_channels: 3
  mean: 0.
  std: 1.
  optimizer:
    class_path: pyro.optim.Adam
    init_args:
      - {lr: 0.001, betas: [0.9, 0.999]}
  criterion:
    class_path: pyro.infer.Trace_ELBO
